name: Test OIDC Auth

on:
  workflow_dispatch:
  
jobs:
  test_auth:
    name: 'Test OIDC Auth'
    runs-on: ubuntu_latest
    permissions:
      contents: read
      id-token: write
      
      
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/628722085506/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider'
          service_account: 'storage-github@govuk-knowledge-graph-dev.iam.gserviceaccount.com'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'GCloud Info'
        run: 'gcloud info'
